class AuthExceptionErrors {
  static const String INTERNAL_ERROR_BLANK_FIELDS =
      'INTERNAL_ERROR_BLANK_FIELDS';
  static const String INTERNAL_ERROR_PASSWORD_CONFIRMATION =
      'INTERNAL_ERROR_PASSWORD_CONFIRMATION';
  static const String INTERNAL_ERROR_BLANK_EMAIL_PASSWORD =
      'INTERNAL_ERROR_BLANK_EMAIL_PASSWORD';

  static const String FIREBASE_ERROR_WRONG_PASSWORD = 'ERROR_WRONG_PASSWORD';
  static const String FIREBASE_ERROR_INVALID_EMAIL = 'ERROR_INVALID_EMAIL';
  static const String FIREBASE_ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
  static const String FIREBASE_ERROR_WEAK_PASSWORD = 'ERROR_WEAK_PASSWORD';
  static const String FIREBASE_ERROR_EMAIL_ALREADY_IN_USE = 'ERROR_EMAIL_ALREADY_IN_USE';

  static const String FIREBASE_ERROR_TOO_MANY_REQUESTS =
      'ERROR_TOO_MANY_REQUESTS';
  static const String FIREBASE_ERROR_NETWORK_REQUEST_FAILED =
      'ERROR_NETWORK_REQUEST_FAILED';
}
